# CI Pipeline Configuration
# Continuous Integration pipeline for automated testing and quality checks

name: CI Pipeline

stages:
  - name: source
    description: "Checkout source code"
    commands:
      - git fetch origin
      - git checkout ${BRANCH_NAME}
      - git pull origin ${BRANCH_NAME}
    
  - name: build
    description: "Build project artifacts"
    commands:
      - echo "Building project..."
      - npm install  # or pip install, mvn install, etc.
      - npm run build
    artifacts:
      - dist/
      - build/
    
  - name: test
    description: "Run automated tests"
    commands:
      - echo "Running tests..."
      - npm test
      - npm run test:coverage
    coverage:
      threshold: 80
      format: lcov
    
  - name: quality
    description: "Code quality and security checks"
    commands:
      - echo "Running quality checks..."
      - npm run lint
      - npm run security-audit
      - npm run code-quality
    quality_gates:
      - code_quality_score: 8.0
      - security_issues: 0
      - code_smells: 10

on_success:
  - notify: "Pipeline completed successfully"
  - upload_artifacts: true

on_failure:
  - notify: "Pipeline failed - check logs"
  - rollback: false
